name: autorelease
on: 
  release:
    types: [created]
jobs:
  upload-vsix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: reselection-commands.vsix
          path: reselection-commands-*.vsix
